### ISSUE TITLE
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

### ISSUE THREAD

**Issue by bandedos** [commercialsuicide/angular2-with-express-starter#3] opened 2017-08-23 12:39 UTC
Hi!

when i execute this command:"ng build -prod -aot" i get this error:
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'
This is error log:
[error.txt](https://github.com/commercialsuicide/angular2-with-express-starter/files/1245375/error.txt)

Can you help me?

Thanks

**Comment by commercialsuicide** [comment] 2017-08-27 00:18
Did you try "$ ng build -prod -aot false"?

**Comment by bandedos** [comment] 2017-08-28 05:05
Thanks for answering. Yes i did try it, and it works.
Where seems to be the problem?

Thanks

**Comment by commercialsuicide** [comment] 2017-09-01 15:24
I don't know where exactly the problem, it's inner Angular CLI problem and I founded the solution at Angular CLI repo. So, if the issue is solved, let me close it.

**Closed by commercialsuicide** 2017-09-01 15:24 UTC
